services:
  postgres:
    image: postgres:15-alpine
    container_name: strategy_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-pump_predictor_strategy}
      POSTGRES_USER: ${DB_USER:-pump_user}
      POSTGRES_PASSWORD: ${DB_PASS:-pump_password}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: